title: Blog majek7x
description: شروحات ومقالات في عالم الأمن السيبراني
author: Hassan 
url: "https://majek7x.github.io"
baseurl: " "

theme:minima

lang: ar
dir: rtl

markdown: kramdown
highlighter: rouge
